https://www.perplexity.ai/search/0eafd6c8-1230-4d5d-9553-446ea1f18997

In [13]:
#學生成績單

import numpy as np
import pandas as pd

scores = np.random.randint(50, 101, size=(50, 5))
scores_pd = pd.DataFrame(scores,columns=['國文','英文','數學','地理','歷史'],index=range(1,51))
scores_pd.T

,1,2,3,4,5,6,7,8,9,10,...,41,42,43,44,45,46,47,48,49,50
國文,82,84,92,62,67,100,59,93,95,60,...,72,50,73,79,62,75,95,97,53,62
英文,72,83,99,95,63,89,51,58,77,70,...,57,94,94,80,97,94,79,78,62,98
數學,81,59,52,51,54,78,86,82,51,68,...,93,62,75,88,68,97,63,86,67,81
地理,81,85,95,51,72,86,90,51,83,90,...,99,64,74,90,52,51,50,82,88,54
歷史,68,61,52,80,96,83,61,61,54,66,...,69,68,94,89,73,93,50,68,59,68

In [14]:
scores_pd.index.name = "學號"
scores_pd.columns.name = "科目"
sum_value = scores_pd.sum(axis=1)
mean_value = np.mean(scores_pd,axis=1)

In [15]:
scores_pd['總分'] = sum_value
scores_pd['平均'] = mean_value

In [16]:
#排序
scores_pd1 = scores_pd.sort_values(by='總分',ascending=False)
scores_pd1

科目   國文  英文   數學  地理  歷史   總分    平均
學號
13   76  94   89  89  99  447  89.4
6   100  89   78  86  83  436  87.2
37   85  86   87  79  93  430  86.0
17   98  83   69  77  99  426  85.2
44   79  80   88  90  89  426  85.2
12   85  93   62  98  87  425  85.0
30   99  92   73  72  77  413  82.6
48   97  78   86  82  68  411  82.2
43   73  94   75  74  94  410  82.0
46   75  94   97  51  93  410  82.0
27   55  94   56  99  97  401  80.2
16   93  57   75  83  91  399  79.8
21   83  80   91  56  87  397  79.4
31   88  59   70  90  90  397  79.4
33   69  60   91  83  91  394  78.8
23   55  58  100  91  89  393  78.6
22   93  62   99  67  70  391  78.2
3    92  99   52  95  52  390  78.0
41   72  57   93  99  69  390  78.0
11   57  84   70  86  91  388  77.6
1    82  72   81  81  68  384  76.8
26   52  74   86  69  99  380  76.0
25   72  60   66  92  89  379  75.8
14   66  81   78  98  55  378  75.6
15   90  57   98  56  75  376  75.2
38   79  55   83  92  65  374  74.8
2    84  83   59  85  61  372  74.4
28   80  54   90  50  91  365  73.0
39   58  75   92  79  60  364  72.8
50   62  98   81  54  68  363  72.6
20   89  55   88  73  58  363  72.6
34   82  87   57  57  79  362  72.4
40   68  84   67  73  70  362  72.4
9    95  77   51  83  54  360  72.0
18   88  98   50  70  51  357  71.4
10   60  70   68  90  66  354  70.8
45   62  97   68  52  73  352  70.4
5    67  63   54  72  96  352  70.4
7    59  51   86  90  61  347  69.4
8    93  58   82  51  61  345  69.0
29   82  62   87  56  56  343  68.6
36   56  59   88  76  62  341  68.2
35   54  68   71  60  87  340  68.0
4    62  95   51  51  80  339  67.8
42   50  94   62  64  68  338  67.6
47   95  79   63  50  50  337  67.4
49   53  62   67  88  59  329  65.8
19   86  50   75  59  55  325  65.0
32   57  68   75  74  50  324  64.8
24   53  63   75  64  68  323  64.6

In [17]:
#排名
scores_pd1['排名'] = scores_pd1['總分'].rank(axis=0,method='min',ascending=False)

In [18]:
scores_pd1
scores_pd1.map(lambda v:float(v))

科目     國文    英文     數學    地理    歷史     總分    平均    排名
學號
13   76.0  94.0   89.0  89.0  99.0  447.0  89.4   1.0
6   100.0  89.0   78.0  86.0  83.0  436.0  87.2   2.0
37   85.0  86.0   87.0  79.0  93.0  430.0  86.0   3.0
17   98.0  83.0   69.0  77.0  99.0  426.0  85.2   4.0
44   79.0  80.0   88.0  90.0  89.0  426.0  85.2   4.0
12   85.0  93.0   62.0  98.0  87.0  425.0  85.0   6.0
30   99.0  92.0   73.0  72.0  77.0  413.0  82.6   7.0
48   97.0  78.0   86.0  82.0  68.0  411.0  82.2   8.0
43   73.0  94.0   75.0  74.0  94.0  410.0  82.0   9.0
46   75.0  94.0   97.0  51.0  93.0  410.0  82.0   9.0
27   55.0  94.0   56.0  99.0  97.0  401.0  80.2  11.0
16   93.0  57.0   75.0  83.0  91.0  399.0  79.8  12.0
21   83.0  80.0   91.0  56.0  87.0  397.0  79.4  13.0
31   88.0  59.0   70.0  90.0  90.0  397.0  79.4  13.0
33   69.0  60.0   91.0  83.0  91.0  394.0  78.8  15.0
23   55.0  58.0  100.0  91.0  89.0  393.0  78.6  16.0
22   93.0  62.0   99.0  67.0  70.0  391.0  78.2  17.0
3    92.0  99.0   52.0  95.0  52.0  390.0  78.0  18.0
41   72.0  57.0   93.0  99.0  69.0  390.0  78.0  18.0
11   57.0  84.0   70.0  86.0  91.0  388.0  77.6  20.0
1    82.0  72.0   81.0  81.0  68.0  384.0  76.8  21.0
26   52.0  74.0   86.0  69.0  99.0  380.0  76.0  22.0
25   72.0  60.0   66.0  92.0  89.0  379.0  75.8  23.0
14   66.0  81.0   78.0  98.0  55.0  378.0  75.6  24.0
15   90.0  57.0   98.0  56.0  75.0  376.0  75.2  25.0
38   79.0  55.0   83.0  92.0  65.0  374.0  74.8  26.0
2    84.0  83.0   59.0  85.0  61.0  372.0  74.4  27.0
28   80.0  54.0   90.0  50.0  91.0  365.0  73.0  28.0
39   58.0  75.0   92.0  79.0  60.0  364.0  72.8  29.0
50   62.0  98.0   81.0  54.0  68.0  363.0  72.6  30.0
20   89.0  55.0   88.0  73.0  58.0  363.0  72.6  30.0
34   82.0  87.0   57.0  57.0  79.0  362.0  72.4  32.0
40   68.0  84.0   67.0  73.0  70.0  362.0  72.4  32.0
9    95.0  77.0   51.0  83.0  54.0  360.0  72.0  34.0
18   88.0  98.0   50.0  70.0  51.0  357.0  71.4  35.0
10   60.0  70.0   68.0  90.0  66.0  354.0  70.8  36.0
45   62.0  97.0   68.0  52.0  73.0  352.0  70.4  37.0
5    67.0  63.0   54.0  72.0  96.0  352.0  70.4  37.0
7    59.0  51.0   86.0  90.0  61.0  347.0  69.4  39.0
8    93.0  58.0   82.0  51.0  61.0  345.0  69.0  40.0
29   82.0  62.0   87.0  56.0  56.0  343.0  68.6  41.0
36   56.0  59.0   88.0  76.0  62.0  341.0  68.2  42.0
35   54.0  68.0   71.0  60.0  87.0  340.0  68.0  43.0
4    62.0  95.0   51.0  51.0  80.0  339.0  67.8  44.0
42   50.0  94.0   62.0  64.0  68.0  338.0  67.6  45.0
47   95.0  79.0   63.0  50.0  50.0  337.0  67.4  46.0
49   53.0  62.0   67.0  88.0  59.0  329.0  65.8  47.0
19   86.0  50.0   75.0  59.0  55.0  325.0  65.0  48.0
32   57.0  68.0   75.0  74.0  50.0  324.0  64.8  49.0
24   53.0  63.0   75.0  64.0  68.0  323.0  64.6  50.0

In [19]:
def calulate(s):
    #return 自訂的series
    custom_series = pd.Series([s.min(),s.max(),s.median(),s.std()],index=["最低分數","最高分數","中間值","標準差"])
    return custom_series
scores_pd1.iloc[:,:5].apply(calulate)

科目            國文         英文          數學         地理         歷史
最低分數   50.000000  50.000000   50.000000  50.000000  50.000000
最高分數  100.000000  99.000000  100.000000  99.000000  99.000000
中間值    77.500000  76.000000   75.000000  76.500000  71.500000
標準差    15.388838  15.440947   14.036396  15.383055  15.674808

In [20]:
def calulate1(s):
    #return 自訂的series
    s_bool = s < 60
    return s_bool.sum()

scores_pd1["不及格的課目"] = scores_pd1.iloc[:,:5].apply(calulate1,axis=1)

In [21]:
scores_pd1

科目   國文  英文   數學  地理  歷史   總分    平均    排名  不及格的課目
學號
13   76  94   89  89  99  447  89.4   1.0       0
6   100  89   78  86  83  436  87.2   2.0       0
37   85  86   87  79  93  430  86.0   3.0       0
17   98  83   69  77  99  426  85.2   4.0       0
44   79  80   88  90  89  426  85.2   4.0       0
12   85  93   62  98  87  425  85.0   6.0       0
30   99  92   73  72  77  413  82.6   7.0       0
48   97  78   86  82  68  411  82.2   8.0       0
43   73  94   75  74  94  410  82.0   9.0       0
46   75  94   97  51  93  410  82.0   9.0       1
27   55  94   56  99  97  401  80.2  11.0       2
16   93  57   75  83  91  399  79.8  12.0       1
21   83  80   91  56  87  397  79.4  13.0       1
31   88  59   70  90  90  397  79.4  13.0       1
33   69  60   91  83  91  394  78.8  15.0       0
23   55  58  100  91  89  393  78.6  16.0       2
22   93  62   99  67  70  391  78.2  17.0       0
3    92  99   52  95  52  390  78.0  18.0       2
41   72  57   93  99  69  390  78.0  18.0       1
11   57  84   70  86  91  388  77.6  20.0       1
1    82  72   81  81  68  384  76.8  21.0       0
26   52  74   86  69  99  380  76.0  22.0       1
25   72  60   66  92  89  379  75.8  23.0       0
14   66  81   78  98  55  378  75.6  24.0       1
15   90  57   98  56  75  376  75.2  25.0       2
38   79  55   83  92  65  374  74.8  26.0       1
2    84  83   59  85  61  372  74.4  27.0       1
28   80  54   90  50  91  365  73.0  28.0       2
39   58  75   92  79  60  364  72.8  29.0       1
50   62  98   81  54  68  363  72.6  30.0       1
20   89  55   88  73  58  363  72.6  30.0       2
34   82  87   57  57  79  362  72.4  32.0       2
40   68  84   67  73  70  362  72.4  32.0       0
9    95  77   51  83  54  360  72.0  34.0       2
18   88  98   50  70  51  357  71.4  35.0       2
10   60  70   68  90  66  354  70.8  36.0       0
45   62  97   68  52  73  352  70.4  37.0       1
5    67  63   54  72  96  352  70.4  37.0       1
7    59  51   86  90  61  347  69.4  39.0       2
8    93  58   82  51  61  345  69.0  40.0       2
29   82  62   87  56  56  343  68.6  41.0       2
36   56  59   88  76  62  341  68.2  42.0       2
35   54  68   71  60  87  340  68.0  43.0       1
4    62  95   51  51  80  339  67.8  44.0       2
42   50  94   62  64  68  338  67.6  45.0       1
47   95  79   63  50  50  337  67.4  46.0       2
49   53  62   67  88  59  329  65.8  47.0       2
19   86  50   75  59  55  325  65.0  48.0       3
32   57  68   75  74  50  324  64.8  49.0       2
24   53  63   75  64  68  323  64.6  50.0       1